In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
data = pd.read_excel(r"C:\Users\Admin\OneDrive\Desktop\Superstore.xlsx")
df = pd.DataFrame(data)

In [9]:
df.head()

  Order Date         Category Sub-Category Region  Product Name  Sales  Profit
0 2023-01-05        Furniture        Chair  North  Office Chair    200      50
1 2023-01-10       Technology        Phone  South        iPhone    800     200
2 2023-02-15  Office Supplies        Paper   East      A4 Paper     50      10
3 2023-02-20        Furniture        Table   West    Wood Table    300     -20
4 2023-03-05       Technology       Laptop  North   Dell Laptop   1200     300

In [11]:
df.isnull().sum()
df.dropna(inplace=True)

In [15]:
df['Month'] = df['Order Date'].dt.month_name()

In [17]:
df['profit_status'] = df["Profit"].apply(lambda x:"loss" if x < 0 else "Profit")
df

,Order Date,Category,Sub-Category,Region,Product Name,Sales,Profit,Month,profit_status
0,2023-01-05,Furniture,Chair,North,Office Chair,200,50,January,Profit
1,2023-01-10,Technology,Phone,South,iPhone,800,200,January,Profit
2,2023-02-15,Office Supplies,Paper,East,A4 Paper,50,10,February,Profit
3,2023-02-20,Furniture,Table,West,Wood Table,300,-20,February,loss
4,2023-03-05,Technology,Laptop,North,Dell Laptop,1200,300,March,Profit
5,2023-03-12,Office Supplies,Pen,South,Ball Pen,20,5,March,Profit
6,2023-04-01,Furniture,Chair,East,Plastic Chair,150,30,April,Profit
7,2023-04-18,Technology,Phone,West,Samsung Phone,700,150,April,Profit
8,2023-05-10,Office Supplies,Paper,North,Notebook,100,25,May,Profit
9,2023-05-22,Furniture,Table,South,Study Table,400,60,May,Profit
10,2023-06-05,Technology,Laptop,East,HP Laptop,1100,250,June,Profit
11,2023-06-18,Office Supplies,Pen,West,Marker,30,8,June,Profit

In [18]:
df['Sales'].sum()

np.int64(5050)

In [20]:
df.groupby('Category')['Sales'].sum()

Category
Furniture          1050
Office Supplies     200
Technology         3800
Name: Sales, dtype: int64

In [21]:
df.groupby('Region')['Sales'].sum()

Region
East     1300
North    1500
South    1220
West     1030
Name: Sales, dtype: int64

In [22]:
df.to_excel("Cleaned_dataset.xlsx",index=False)